name: Build APK with CMake 3.16.5

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:

jobs:
  build:
    name: Build APK
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Set up JDK 17
      uses: actions/setup-java@v3
      with:
        distribution: 'temurin'
        java-version: '17'

    - name: Set up Android SDK
      uses: android-actions/setup-android@v3

    - name: Install required SDK packages
      run: |
        yes | sdkmanager --licenses
        sdkmanager --install "ndk;21.4.7075529" "platform-tools" "platforms;android-30" "build-tools;30.0.3"

    - name: Install CMake 3.16.5 manually
      run: |
        mkdir -p $ANDROID_HOME/cmake
        wget https://github.com/Kitware/CMake/releases/download/v3.16.5/cmake-3.16.5-Linux-x86_64.tar.gz
        tar -xzf cmake-3.16.5-Linux-x86_64.tar.gz
        mv cmake-3.16.5-Linux-x86_64 $ANDROID_HOME/cmake/3.16.5
        echo "$ANDROID_HOME/cmake/3.16.5/bin" >> $GITHUB_PATH

    - name: Grant permission to gradlew
      run: chmod +x ./gradlew

    - name: Use Gradle 6.5 via wrapper
      run: ./gradlew wrapper --gradle-version 6.5 --stacktrace

    - name: Build Debug APK
      run: ./gradlew assembleDebug

    - name: Upload Debug APK
      uses: actions/upload-artifact@v4
      with:
        name: mod-android-client-debug.apk
        path: app/build/outputs/apk/debug/app-debug.apk
