name: Build APK (Gradle 6.5 + CMake 3.16.5)

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up JDK 11
      uses: actions/setup-java@v3
      with:
        distribution: 'temurin'
        java-version: '17'

    - name: Set up Gradle 6.5
      uses: gradle/actions/setup-gradle@v3
      with:
        gradle-version: '6.5'

    - name: Set up Android SDK
      uses: android-actions/setup-android@v3

    - name: Install CMake 3.16.5 & required tools
      run: |
        yes | sdkmanager --install "cmake;3.16.5" "ndk;21.4.7075529" "platform-tools" "platforms;android-30"
        sdkmanager --list | grep cmake

    - name: Grant gradlew permission
      run: chmod +x ./gradlew

    - name: Build Debug APK
      run: ./gradlew assembleDebug

    - name: Upload APK artifact
      uses: actions/upload-artifact@v4
      with:
        name: mod-android-client-debug.apk
        path: app/build/outputs/apk/debug/app-debug.apk
