name: Build Android APK

on:
  workflow_dispatch:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    # JDK 17 для sdkmanager
    - name: Set up JDK 17 (for sdkmanager)
      uses: actions/setup-java@v3
      with:
        java-version: '17'
        distribution: 'temurin'

    - name: Set up Android SDK
      uses: android-actions/setup-android@v3

    - name: Install SDK packages except CMake
      run: |
        yes | sdkmanager --install \
          "ndk;21.4.7075529" \
          "build-tools;30.0.3" \
          "platforms;android-30" \
          "platform-tools"

    - name: Install CMake 3.16.5 manually
      run: |
        mkdir -p $ANDROID_SDK_ROOT/cmake
        wget https://github.com/Kitware/CMake/releases/download/v3.16.5/cmake-3.16.5-Linux-x86_64.tar.gz
        tar -xzf cmake-3.16.5-Linux-x86_64.tar.gz
        mv cmake-3.16.5-Linux-x86_64 $ANDROID_SDK_ROOT/cmake/3.16.5
        echo "$ANDROID_SDK_ROOT/cmake/3.16.5/bin" >> $GITHUB_PATH

    # JDK 11 для сборки Gradle
    - name: Set up JDK 11 (for Gradle build)
      uses: actions/setup-java@v3
      with:
        java-version: '11'
        distribution: 'temurin'

    - name: Make gradlew executable
      run: chmod +x ./gradlew

    - name: Build APK
      run: ./gradlew assembleDebug --stacktrace --info

    - name: Upload APK artifact
      uses: actions/upload-artifact@v4
      with:
        name: my-app-debug-apk
        path: app/build/outputs/apk/debug/app-debug.apk
