name: Build APK

on:
  workflow_dispatch:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:

jobs:
  build:
    name: Build with Gradle 6.5 and CMake 3.16.5
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Set up JDK 11
      uses: actions/setup-java@v3
      with:
        distribution: 'zulu'
        java-version: '11'

    - name: Set up Android SDK
      uses: android-actions/setup-android@v3

    - name: Install CMake 3.16.5
      run: |
        sudo apt-get update
        sudo apt-get install -y cmake
        sudo cmake --version

    - name: Configure Android SDK CMake
      run: |
        sdkmanager --install "cmake;3.16.5"
        sdkmanager --install "ndk;21.4.7075529" # если проект требует NDK

    - name: Grant execute permission to gradlew
      run: chmod +x ./gradlew

    - name: Use Gradle Wrapper with version 6.5
      run: |
        ./gradlew wrapper --gradle-version 6.5
        ./gradlew --version

    - name: Build Debug APK
      run: ./gradlew assembleDebug

    - name: Upload Debug APK
      uses: actions/upload-artifact@v4
      with:
        name: app-debug.apk
        path: app/build/outputs/apk/debug/app-debug.apk
